Fix ts types
react-native-svg/react-native-svg pull request #1628
Opened 2021-08-11 01:31 UTC by douglowder

# Summary

Fix a large number of errors in TS type generation:

- Update `@types/react` and `@types/react-native`
- Make required changes in some of the components in `src/elements`

## Test Plan

After the change, `npm install` succeeds in building the package.

2021-08-11 01:37 UTC, douglowder commented
@brentvatne this branch succeeds with `npm install` and `npm test`.

2021-08-11 23:07 UTC, brentvatne requested changes
need to add back `extract` for global properties

2021-08-11 23:30 UTC, douglowder commented on src/elements/Circle.tsx
> -        {...extract(this, props)}
Ok I'll fix that and add some tests as well

2021-08-12 20:15 UTC, douglowder commented on src/elements/Circle.tsx
> -        {...extract(this, props)}
@brentvatne I restored the `extract(this, props)` in the affected elements.  Testing with the SVG examples looks good.  I'll try to do some snapshot tests to verify that all SVGs are rendered the same as before.

2021-08-13 02:03 UTC, brentvatne commented
any idea why the package-lock.json diff is so huge, given that we're just updating two `@types` packages?

2021-08-13 04:13 UTC, douglowder commented
I had to delete it in order to run npm install. There were missing package files and conflicts if I didn't do that.

2021-08-13 17:58 UTC, brentvatne approved these changes

2021-08-13 17:58 UTC, merged